### PR TITLE
Create debian package

### PR DESCRIPTION
**Pull request by fliphess**
Hey Patrik!

I made some changes in the structure of the repository, moved some "extras" around and created a debian package that you can build for both debian and ubuntu. 

I'm not sure if you are interested in my packaging, and if this is the way to go, so please let me know if i should refactor before merging, or that i just keep it to myself :) 

I love rdiffweb and needed some easy way of deploying on my testing/staging and production server so i spend some time to package the whole bunch. 

At the moment the webui is running as an unprivileged user, but mabe this is not the way to do it (i'd like another layer of security as in not running as root, but let me know if this will suffice) 

For now i moved the logrotate and init script into the debian directory, so dh_init and dh_logrotate will do the job instead of setuptools. 

I also moved the package dependencies to a separate file for development, so i could install these in my cowbuilder environment from the build-depends

The buildme script is a/my common way of versioning debian packages, but this can be easily changed if you prefer to keep your releases in line with your current numbering.

I squashed all my commits together as i did a lot of crufty commits in between builds. 

Let me know if you can use it! 

Regards, Flip

### CODE REVIEW

**Comment by ikus060** [comment]
This sound very nice ! I had plan to do it, but I never created any debian package before. I'm glad you did it ! Before I commit this to master, I will need to review your modification. I probably have question for you, as I need to maintain this after.

I see a buildme.sh file. I might use this to build rdiffweb automatically using my jenkins server.

I will try to review your changes by the end of the day (EST time) Thanks !

**Comment by fliphess** [comment]
Ah cool! Jenkins definately is the way to do it :) Keep me in the loop, if i need to change anything i can :)

**Comment by ikus060** [comment]
buildme.sh
1. The version definitely need to matches our version. Is it possible to append the date to the version to have unique build everytime ? Maybe we need to add the branch name too or something to distinguish the debian package generate in `develop` branch vs `master` branch
2. Why to you define `--git-arch=amd64`. I think it should be `noarch`.
3. I probably need to tweak this file, since I'm using Jenkins to build rdiffweb. I have two different need: 
 * (1) generate a debian package for every git push: this is to run the unit test, the automated integration test and to run static code analysis.
 * (2) generate a release: the release should first build and run the test, then if everything is OK, update the changelog, generate the debian package, then create tag and publish the debian package to my website or via dput.
Do you have any suggestions on the subject ? I'm used to Java/Maven projects where the maven-release-plugin take care of this.
4. I'm not familar with dput. Does it send the package to a ubuntu ppa ? or to debian repo ?

debian/control:
1. `X-Python-Version: >= 2.4` is probably wrong. I'm sure rdiffweb is not running on python 2.4 anymore. I'm using alot of python 2.7 stuff.

debian/copyright:
1. The copyright date should be 2015. I probably need to update the copyright date everywhere alos ;-)

debian/rdiffweb.init:
1. I don't understand why you changed line 75-80: start-stop-daemon commands.

**Comment by ikus060** [comment]
Also, I didn't manage to run `git-buildpackage` with ` --git-pbuilder`. It does some magic that I don't know of.

**Comment by fliphess** [comment]
Hey Patrik, i will create a script for you that you can use to setup a debian build environment, so you can use that for testing and with jenkins :) Im at work atm, but when i'm finished i'll get to it :)

**Comment by fliphess** [comment]
Hey @ikus060

I wrote a script to setup an Ubuntu build environment, that you can use to setup an environment and create cows to build your package in.

The script to setup a cowbuilder environment can be found [here](https://gist.github.com/fliphess/9cffebbe8421189da931).

A cow is a very minimal ubuntu or debian debootstrapped chroot with no additional packages installed. By using cows to build, its easier to test if your listed dependencies are sufficient for the package you are about to build.
I've been looking for a way to use docker for this, but as it's hard to find out whats in the base docker, its hard to determine if you have all dependencies listed in the control file.

I found this text from an article what pretty much covers the why a bit:

```
    For many the obvious way to achieve this is to just run dpkg-buildpackage, but this is not enough to ensure that the package will build once it is uploaded to Ubuntu.

    Using dpkg-buildpackage you won't know if there's some build dependency missing in debian/control if you already have it installed, stuff on your system may influence the build process, and so on.

    Even further, the package you're creating is most likely intended for the current development version of Ubuntu (at the time of writing this, Jaunty) but you are still running the stable release (Intrepid), or the release is the same but having to pollute your system with all dependencies needed to build a package is not ideal. I guess you get the point…

```

I chose to build in an ubuntu trusty chroot, but this can be easily changed as you like. I'm not sure if it matters at all whether you use a debian or ubuntu chroot, as the package dependencies are equal and so are the names, the config files or the build process. 

I have removed the buildme script from the PR, because you might want to do this using your own jenkins scripts.

I split the buildme into 2 separate scripts usable as an example for building with jenkins:
* A script to build a package [here](https://gist.github.com/fliphess/63a234e1f3d1a40ee8e8).
* A script to do a release by creating a new tag and updating the changelog, and then do a package build [here](https://gist.github.com/fliphess/cb776a2ed0ab82c193f2).

The second script/example can (with some adjustments) be used to do nighly builds or development snapshots or something like it as well, as it will do some autoversioning when the development branch is used to build from.

With the versioning system you suggested in your previous comment I ran into some problems.
I'm affraid that the exact current version is not possible when packaging, as debian and ubuntu versions do not take non-digits as the first character of the version.

The debian packaging policy about packaging [here](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version) sort of states:

    The upstream_version may contain only alphanumerics and the characters . + - : (full stop, plus, hyphen, colon) and should start with a digit.


Which means you could leave out the epoch which defaults to 0: which is acceptable for just the package version, but the should start with a digit is a bit of a p in the a as the versions are v[0-9]+ based.
You could put the timestamp in front of the version, which makes its debian (ubuntu) version something like 0:20150509.v7 but its still not the same.... Anyhow i took out the build script and left you with some example scripts...
I think this is for you to decide :)

As you allready noticed the build script mentions the arch is amd64, as this is the arch of the cow the package will be build in. The resulting debian/ubuntu packages will have no mention whatsoever of any arch. Instead it will use ```_all``` as the rdiffweb is not arch depending.

After building, one dir below (..) your git repository all the deb files etc are stored after build, which can be easily send to a launchpad ppa or a private repository using [dput](https://help.launchpad.net/Packaging/PPA/Uploading)

debian/control: [x] updated!
debian/copyright: [x] updated and all the other 2014's as well!

debian/rdiffweb.init: I added the first only the -u (user) and -g (group) flag, but could only get it to run as a non privileged user by using both -u/-g AND --chuid.. So i added them both. (I restructured it a bit again re-adding the page breaks) Any suggestions? 

debian/rules: You can run the testsuite prior to the build process from de rules file, how is the testsuite run? Then i'll adjust it accordingly

Let me know if this is okay for you, if you need more info or my skype or what i should change to make it better :)

(i think i should restructure this PR anyway as it should go into the develop branch i presume, so if i should split some things into separate pull requests let me know)

**Comment by ikus060** [comment]
I hate this kind of build where you need hundred of different packages to make stuff work. I so love maven for this reason.

I've create a new Jenkins Jobs named `rdiffweb_master_deb` to create a debian package. Correct me if I'm wrong.: I should re-create the cow environment on every build. So I need to call `git-pbuilder create` every time.

I first use your script to initialize/configure pbuilder, but it causes me more trouble since I'm using debian wheezy, not ubuntu. When running `git-pbuilder create` I had the following error log. Notice the `sid` ditribution. ?!
```
[workspace] $ /bin/sh -xe /tmp/hudson4428605517839062343.sh
+ export DIST=trusty
+ export BASE=/var/cache/pbuilder/base-trusty/
+ sudo git-pbuilder create
 -> Invoking pbuilder
  forking: pbuilder create --buildplace /var/cache/pbuilder/base.cow --mirror http://nl.archive.ubuntu.com/ubuntu/ --distribution sid --no-targz --extrapackages cowdancer 
W: /root/.pbuilderrc does not exist
I: Running in no-targz mode
I: Distribution is sid.
I: Current time: Sat May  9 12:55:56 EDT 2015
I: pbuilder-time-stamp: 1431190556
I: Building the build environment
I: running debootstrap
/usr/sbin/debootstrap
I: Retrieving Release
E: Failed getting release file http://nl.archive.ubuntu.com/ubuntu/dists/sid/Release
E: debootstrap failed
W: Aborting with an error
pbuilder create failed
  forking: rm -rf /var/cache/pbuilder/base.cow 
Build step 'Execute shell' marked build as failure
Recording test results
Finished: FAILURE
```

I've remove the file `/etc/pbuilderrc`, `/etc/git-buildpackage/hooks/D40-speedup-hacks` and `/etc/git-buildpackage/hooks/D50-setup-cow-apt` previously created by your script. I'm now successfully creating a cow environment when running `git-pbuilder create`.

**Comment by fliphess** [comment]
Hey @ikus060 

I use trusty myself but i can do the same thing for debian, i'll just adapt the script... I have a debian server too, so i just adapted it for wheezy [here](https://gist.github.com/fliphess/c01298a307c5c23fcc56)

You can do without the config if you prefer.. Also mabe it's wise to use a more local mirror then the one in amsterdam i'm using now :) 

I think the packaging mechanism for debian and ubuntu is made for people with long grey beards and years of unix-caving i think, as it's in no way to be called user-friendly or uncomplicated :) 

You don't have to create a new cow environment on every build. Just run the setup script once and after that git-pbuilder clones the base-cow on every build and builds inside this chroot. After the build the old cow is thrown away when the build succeeds.
If you want to refresh your cow you can do rm -rf /var/cache/pbuilder/*.cow and then rerun the setup script: 
    ./create-debian-build-environment.sh create_cow

Only if you want to recreate the cow or make changes you should make changes in the cow base. (i don't recommend doing this by hand as i like to throw away my cows now and then. Better use the hooks to handle this stuff)

**Comment by ikus060** [comment]
Thanks alot for your help on this. I now have a better understanding of the build solution to create a deb.
I've rename my job `rdiffweb_master_deb` into `rdiffweb_master_debian_wheezy_amd64`. This job is responsible to create a deb. It's only run when a previous job, responsible to compile rdiffweb, is successful. Basically, this job run `sudo git-buildpackage --git-pbuilder --git-dist=wheezy --git-arch=amd64`. Using a different job to generate a deb allows me to, later-on, create separate deb for each platform if required.
It seams to do the job very well. In the end, I have a new `.deb` file. I didn't test the deb file yet. 

The resulting deb is named `rdiffweb_0v7.1_amd64.deb`. I don't understand where `0v7.1`is comming from. The versionning it's obsiouly wrong. I will need your help to fix this. ;)
Full log: https://gist.github.com/ikus060/75715004c0beeb01f9dc
I guess it's some kind of magic using git tags to determine the next version number. This logic seams off   for me and doesn't really follow how we are working here. Unless there is a mechanism to auto update the source code (setup.py) with the right version number, which I doubt, the REAL version number is consider to be the setup.py, not git tags. Following this idea, the version from setup.py should be used. Not git tags version. Best would be to use the version from setup.py (0.7.0), append the date to it (0.7.0.20150509).

As for your commits, I recommend to
* Squash most of them into a single commits.
* Keep the copyright update apart.
* Submit a push request to master. It doesn't change the code base. For me it's still 0.7.0 or let name it 0.7.1. It's only packaging changes.

**Comment by ikus060** [comment]
Did you have chances to progress on this pull request ?

**Comment by fliphess** [comment]
Hey man! I was on holiday for 2 weeks so i wasn't able to look into it.
I'll get to it this week!




Met vriendelijke groet,

Flip Hess'

-- --

Byte B.V.
De Ruyterkade 139
1011 AC Amsterdam
T: +31 (0) 20 5216 226
W: http://www.byte.nl
E: flip@byte.nl

**Pull request closed without merging**
